### PR TITLE
Token info validation

### PR DESCRIPTION
**Pull request by amarinkovic**
It should not be possible to set a token symbol or name of arbitrary size.

### CODE REVIEW

**Comment by melks** [comment]
Task linked: [CU-8692zqxj7 An attacker can fill up data on a tokenized object to cause a mass gas consumption](https://app.clickup.com/t/8692zqxj7)

**Comment by melks** [comment]
Task linked: [CU-8692zqxj7 An attacker can fill up data on a tokenized object to cause a mass gas consumption](https://app.clickup.com/t/8692zqxj7)

**Comment by melks** [comment]
Task linked: [CU-8692zqxj7 An attacker can fill up data on a tokenized object to cause a mass gas consumption](https://app.clickup.com/t/8692zqxj7)

**Review by kevin-fruitful — APPROVED** [review]
Should we use custom errors or nawww

**Comment by amarinkovic** [comment]
> Should we use custom errors or nawww

Maybe at a later point, I don't want to spend more time on it at the moment.

**Pull request merged**
