### PR TITLE
Order book sorting problem with small amounts

### PR DESCRIPTION
**Pull request by amarinkovic**
This pull request fixes the issue with order book sorting caused by an edge case when the unsettled amounts on an existing offer are very small.

Bug was originally reported through Immunefi: [IM-24299](https://bugs.immunefi.com/dashboard/submission/24299)

### CODE REVIEW

**Comment by melks** [comment]
Task linked: [CU-8692xw1kp An attacker can mess up the sorted list of offers (IM-24299)](https://app.clickup.com/t/8692xw1kp)

**Comment by melks** [comment]
Task linked: [CU-8692xw1kp An attacker can mess up the sorted list of offers (IM-24299)](https://app.clickup.com/t/8692xw1kp)

**Comment by melks** [comment]
Task linked: [CU-8692xw1kp An attacker can mess up the sorted list of offers (IM-24299)](https://app.clickup.com/t/8692xw1kp)

**Review by kevin-fruitful — APPROVED** [review]

**Comment by imp0wd3r** [comment]
Hello, I submitted #25031 on Immunefi. Your response mentioned that it was duplicated with this vulnerability. I believe these two vulnerabilities are different, and the mentioned PR has not fixed the issue I brought up in #25031. Please take another look. Thank you.

**Pull request merged**
