### PR TITLE
Simple policy signing updates

### PR DESCRIPTION
**Pull request by amarinkovic**
Update simple policy signing and verification

### CODE REVIEW

**Comment by melks** [comment]
Task linked: [CU-861m4mwby Update policy signing procedure (smart contracts + FE + BE)](https://app.clickup.com/t/861m4mwby)

**Comment by kevin-fruitful** [comment]
Did we still want to include the check that policy stakeholders are entity admins? LibEntity line 132.

**Comment by amarinkovic** [comment]
This is currently how we validate what's being signed. If from recreated signing hash, we recover a signer who is admin on the corresponding entity, we assume signing hash is valid and we accept the entity as a stakeholder on the policy.

**Comment by amarinkovic** [comment]
No, we should just check for parent, good point.

**Comment by kevin-fruitful** [comment]
lgtm!

**Review by kevin-fruitful — APPROVED** [review]

**Pull request merged**
